version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pub
    directory: /01_code/citypulse-IDP/app
    schedule:
      interval: monthly
  - package-ecosystem: pub
    directory: /01_code/citypulse-IDP/services/router_api
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /01_code/citypulse-IDP/server
    schedule:
      interval: monthly
