"""Writes the repository-root `Dockerfile` and `.dockerignore` from deploy/single/Dockerfile.

Why: some hosts (Render's default, for one) look for `Dockerfile` at the top of the Git repository and use the top as the
build context. This project lives in a subfolder (01_code/citypulse-IDP), so the one-container image is defined once, in
deploy/single/Dockerfile, and the root copy is generated from it by prefixing every COPY source with that subfolder. Never edit
the root files by hand: change deploy/single/Dockerfile and run

    python scripts/make_root_dockerfile.py

`scripts/tests/test_root_dockerfile.py` fails when the root files are out of date.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE.parent                      # 01_code/citypulse-IDP
REPO = APP.parent.parent               # the Git repository root
PREFIX = "01_code/citypulse-IDP"

HEADER = (
    f"# GENERATED by {PREFIX}/scripts/make_root_dockerfile.py from {PREFIX}/deploy/single/Dockerfile. Do not edit by hand.\n"
    "# This copy exists for hosts that expect `Dockerfile` at the top of the repository (build context = repository root).\n"
    "# To build by hand from the repository root:  docker build -t citypulse .\n"
)


def root_dockerfile(master: str) -> str:
    out = []
    for line in master.splitlines():
        m = re.match(r"^(COPY)(\s+--\S+)*\s+(.+)$", line)
        if line.startswith("COPY") and "--from=" not in line and m:
            parts = line.split()[1:]
            *sources, dest = parts
            line = "COPY " + " ".join(f"{PREFIX}/{s}" for s in sources) + " " + dest
        out.append(line)
    return HEADER + "\n".join(out) + "\n"


def root_dockerignore(master_ignore: str) -> str:
    out = [
        f"# GENERATED by {PREFIX}/scripts/make_root_dockerfile.py from {PREFIX}/.dockerignore. Do not edit by hand.",
        "# Build context = repository root, so every pattern below is prefixed with the project folder.",
        "*",
        f"!{PREFIX}",
        "",
        "# Inside the project folder (allow-list copied from its .dockerignore; the root '*' above lets the folder in, these narrow it):",
        f"{PREFIX}/*",
    ]
    for raw in master_ignore.splitlines():
        s = raw.strip()
        if not s or s.startswith("#") or s == "*":
            continue
        if s.startswith("!"):
            out.append(f"!{PREFIX}/{s[1:]}")
        elif s.startswith("**/"):
            out.append(s)
        else:
            out.append(f"{PREFIX}/{s}")
    return "\n".join(out) + "\n"


def build() -> tuple[str, str]:
    master = (APP / "deploy" / "single" / "Dockerfile").read_text(encoding="utf-8")
    ignore = (APP / ".dockerignore").read_text(encoding="utf-8")
    return root_dockerfile(master), root_dockerignore(ignore)


def main() -> int:
    dockerfile, ignore = build()
    (REPO / "Dockerfile").write_text(dockerfile, encoding="utf-8", newline="\n")
    (REPO / ".dockerignore").write_text(ignore, encoding="utf-8", newline="\n")
    print(f"wrote {REPO / 'Dockerfile'} and {REPO / '.dockerignore'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
