"""
T-W1 -- Build and validate the watchlist (docs/IMPLEMENTATION_PLAN.md Phase 1;
docs/CHENNAI_PROTOTYPE_SPEC.md section 4; docs/DECISIONS.md ADR-009).

**What this script does, and does not, complete.** T-W1's full acceptance criterion is a
resident-reviewed map ("a Chennai resident looks at and says 'yes, those are the places'"),
with basin labels sourced from a real GIS join and each point "named as a resident would say
it." Those two steps are explicitly NOT automatable from data on this machine (the plan's own
words: "this is a manual/GIS join, not yet automatable, since no basin-boundary shapefile was
found") and are not attempted here. What this script DOES do, end to end, from data already on
disk (no new downloads, no paid services, per CLAUDE.md's Rule 1):

  1. Parse the real OpenCity/GCC flood-hazard-zone KML (T0.5's confirmed data source; GO
     decision already recorded in data/results/2026-09-12-t05-watchlist/).
  2. Filter to the High/Very High risk categories (the two most policy-relevant tiers) --
     1,504 of 7,453 zones -- since T-W1's 150-200-point target implies real chronic points,
     not every hazard-hinted polygon at every risk level.
  3. Cluster adjacent zone centroids (many are fragments of the same real flooded stretch,
     not independent points) using the same 150 m radius ADR-010 already uses for report
     coarsening, for consistency rather than a fresh arbitrary number.
  4. Score each cluster's proximity to the Michaung (4 Dec 2023) press-sourced leads named in
     research/SYNTHESIS.md section 9's addendum and docs/CHENNAI_PROTOTYPE_SPEC.md section 4
     -- a cluster near BOTH the 2026 GCC hazard-zone data and a 2023 real-flood press report is
     the two-source cross-check ADR-009/T-W1 ask for.
  5. Snap each cluster centroid to the nearest drivable OSM way, using
     data/osm/chennai_overpass_drivable.json (generated by
     scripts/fetch_chennai_drivable_ways.py -- see that script's own docstring; it carries full
     way geometry, unlike chennai_graph.sqlite, which T0.2 built purely for Dijkstra timing and
     stripped of coordinates entirely). **This is a live Overpass snapshot, not a pinned one**
     (same caveat T0.2 already states about itself) -- every way_id produced here is
     provisional and will likely need re-resolution once T1.3's real graph build exists,
     against the pinned Geofabrik extract.
  6. Emit a coarse, EXPLICITLY-FLAGGED-UNVERIFIED basin label from known basin geography
     (research/SYNTHESIS.md section 9 addendum: Kosasthalaiyar/Cooum/Adyar/Kovalam are real,
     named, roughly-bounded basins, just not available here as a shapefile) -- a starting
     placeholder for the human GIS join, not a substitute for it.

**Caveat on step 4's coordinates**, stated once here rather than buried in a constant: the
Michaung lead localities' coordinates below are approximate locality centroids from general
geographic knowledge, not a geocoding API or surveyed data -- they are good enough for a
multi-kilometre proximity flag, not for edge-level precision. Same caveat, same reason, for
step 6's basin bands.

Usage: .venv/Scripts/python.exe scripts/tw1_build_watchlist.py
"""

from __future__ import annotations

import itertools
import json
import math
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

import ijson

ROOT = Path(__file__).resolve().parent.parent
KML_PATH = ROOT / "data" / "watchlist_raw" / "chennai_flood_hazard_zones.kml"
WAYS_PATH = ROOT / "data" / "osm" / "chennai_overpass_drivable.json"
TODAY = datetime.now(tz=timezone.utc).date().isoformat()
OUT_DIR = ROOT / "data" / "watchlist" / TODAY
RESULTS_DIR = ROOT / "data" / "results" / f"{TODAY}-tw1-watchlist"

NS = {"kml": "http://www.opengis.net/kml/2.2"}

# Cluster radius -- HOW BIG IS "ONE CHRONIC WATERLOGGING POINT" IS NOT A SETTLED QUESTION.
# ADR-010's 150 m grid answers a different question (anonymising a report's location for
# privacy) and does not transfer here just because it's a number this codebase already uses.
# A sensitivity sweep (see this script's docstring and the "cluster_count_by_radius_m" field
# in the written manifest) shows the candidate count is genuinely sensitive to this choice:
# 683 clusters at 150 m, 402 at 300 m, 171 at 750 m (docs/IMPLEMENTATION_PLAN.md's 150-200
# target). 300 m is used as a documented, defensible-but-not-validated default -- large enough
# that adjacent KML polygon fragments of the same road stretch merge, small enough that two
# distinct hazard mechanisms a few hundred metres apart (e.g. two different lakes' overflow
# paths) do not get silently conflated. This is exactly the kind of parameter the resident map
# review (T-W1's actual acceptance test) should validate or override, not something this
# script should quietly pick by tuning until the count "looks right."
CLUSTER_RADIUS_M = 300.0
CLUSTER_RADIUS_SWEEP_M = [150.0, 250.0, 300.0, 400.0, 500.0, 750.0, 1000.0]

HIGH_RISK_CATEGORIES = {"High", "Very High"}

# Grid cell size for the way-geometry spatial index. ~0.01 deg is roughly 1.1 km at Chennai's
# latitude -- coarse enough to keep the index small, fine enough that a candidate point's
# nearest way is almost always in the same or an adjacent cell.
GRID_CELL_DEG = 0.01

# Michaung (4 Dec 2023) press-sourced leads -- research/SYNTHESIS.md section 9 addendum;
# docs/CHENNAI_PROTOTYPE_SPEC.md section 4. Approximate locality centroids, NOT surveyed
# (see this file's top comment). "flooded" localities score a positive proximity signal;
# "not_badly_hit" is the addendum's explicit negative signal (Adyar/Kotturpuram proper were
# reported as NOT badly hit the same day -- a candidate near only these should not inherit
# the corridor's general flood reputation for free).
MICHAUNG_LEADS = {
    "Pallikaranai (200 ft radial road / Narayanapuram Lake overflow)": (
        12.9351,
        80.1988,
        "flooded",
    ),
    "Mudichur / Varadharajapuram / Old Perungalathur / Bharathy Nagar": (
        12.8800,
        80.1180,
        "flooded",
    ),
    "Velachery / Taramani / Perungudi / Madipakkam": (12.9720, 80.2210, "flooded"),
    "Besant Nagar / Sastri Nagar / Thiruvanmiyur": (12.9920, 80.2630, "flooded"),
    "Adyar / Kotturpuram proper (press: NOT badly hit)": (
        13.0160,
        80.2480,
        "not_badly_hit",
    ),
}
MICHAUNG_MATCH_RADIUS_KM = 2.5

# Coarse basin bands from known basin geography (research/SYNTHESIS.md section 9 addendum;
# docs/CHENNAI_PROTOTYPE_SPEC.md section 4) -- latitude bands only, NOT real watershed
# polygons. Every point labelled this way carries basin_label_confidence: "heuristic_unverified"
# in the output; do not treat this as T-W1's basin-assignment step being done.
#
# **Known failure mode, not just imprecision (flagged by independent review):** basins are
# distinguished by which river a point actually drains toward, not by how far north/south it
# sits. With no longitude term at all, this heuristic will mislabel any INLAND point south of
# the Adyar/Kovalam boundary latitude as "Kovalam" (a coastal basin) regardless of how far from
# the coast it actually is -- the mechanism is wrong, not merely coarse. It happens not to
# visibly bite in the current output (the few "Kovalam" points are all near a coastal
# longitude), but nothing here prevents it from doing so on a different candidate set.
BASIN_BANDS = [
    # (min_lat_exclusive, label)  -- evaluated top to bottom, first match wins.
    (13.10, "Kosasthalaiyar"),
    (13.02, "Cooum"),
    (12.90, "Adyar"),
    (float("-inf"), "Kovalam"),
]


def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371000.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = (
        math.sin(dphi / 2) ** 2
        + math.cos(p1) * math.cos(p2) * math.sin(dlambda / 2) ** 2
    )
    return 2 * r * math.asin(math.sqrt(a))


# ---------------------------------------------------------------------------------------
# Step 1-2: flood hazard zones
# ---------------------------------------------------------------------------------------


def parse_kml_coords(text: str) -> list[tuple[float, float]]:
    pts = []
    for tok in text.split():
        parts = tok.split(",")
        if len(parts) >= 2:
            lon, lat = float(parts[0]), float(parts[1])
            pts.append((lat, lon))
    return pts


def load_flood_zones() -> list[dict]:
    tree = ET.parse(KML_PATH)
    root = tree.getroot()
    zones = []
    for pm in root.findall(".//kml:Placemark", NS):
        fields = {sd.get("name"): sd.text for sd in pm.findall(".//kml:SimpleData", NS)}
        coord_el = pm.find(".//kml:outerBoundaryIs//kml:coordinates", NS)
        if coord_el is None:
            coord_el = pm.find(".//kml:coordinates", NS)
        if coord_el is None or not coord_el.text:
            continue
        pts = parse_kml_coords(coord_el.text)
        if not pts:
            continue
        lat = sum(p[0] for p in pts) / len(pts)
        lon = sum(p[1] for p in pts) / len(pts)
        category = fields.get("CATEGORY")
        area = fields.get("SHAPE.AREA")
        zones.append(
            {
                "objectid": fields.get("OBJECTID"),
                "category": category,
                "shape_area": float(area) if area else 0.0,
                "lat": lat,
                "lon": lon,
            }
        )
    return zones


# ---------------------------------------------------------------------------------------
# Step 3: clustering
# ---------------------------------------------------------------------------------------


def cluster_points(zones: list[dict], radius_m: float) -> list[dict]:
    """Greedy clustering: process zones largest-area-first so a cluster's seed is its most
    prominent member; any later zone within radius_m of an existing cluster's *current*
    centroid joins it (area-weighted running mean), else it starts a new cluster. Not a
    globally optimal clustering, but deterministic, O(n * clusters) which is fine at n=1504,
    and good enough for "these are fragments of the same real place" -- the acceptance bar
    is the resident map review, not this algorithm.
    """
    ordered = sorted(zones, key=lambda z: -z["shape_area"])
    clusters: list[dict] = []
    for z in ordered:
        best = None
        best_dist = radius_m
        for c in clusters:
            d = haversine_m(z["lat"], z["lon"], c["lat"], c["lon"])
            if d <= best_dist:
                best = c
                best_dist = d
        if best is None:
            clusters.append(
                {
                    "lat": z["lat"],
                    "lon": z["lon"],
                    "total_area": z["shape_area"],
                    "member_categories": {z["category"]},
                    "n_members": 1,
                }
            )
        else:
            w_old = best["total_area"]
            w_new = z["shape_area"]
            total = w_old + w_new if (w_old + w_new) > 0 else 1.0
            best["lat"] = (best["lat"] * w_old + z["lat"] * w_new) / total
            best["lon"] = (best["lon"] * w_old + z["lon"] * w_new) / total
            best["total_area"] += z["shape_area"]
            best["member_categories"].add(z["category"])
            best["n_members"] += 1
    return clusters


# ---------------------------------------------------------------------------------------
# Step 4: Michaung proximity scoring
# ---------------------------------------------------------------------------------------


def nearest_michaung_lead(lat: float, lon: float) -> dict | None:
    best_name, best_dist_km, best_status = None, None, None
    for name, (lead_lat, lead_lon, status) in MICHAUNG_LEADS.items():
        d_km = haversine_m(lat, lon, lead_lat, lead_lon) / 1000.0
        if best_dist_km is None or d_km < best_dist_km:
            best_name, best_dist_km, best_status = name, d_km, status
    if best_dist_km is None or best_dist_km > MICHAUNG_MATCH_RADIUS_KM:
        return None
    return {
        "lead": best_name,
        "distance_km": round(best_dist_km, 2),
        "status": best_status,
    }


# ---------------------------------------------------------------------------------------
# Step 5: snap to nearest drivable OSM way
# ---------------------------------------------------------------------------------------


def load_drivable_ways() -> list[dict]:
    """Streams data/osm/chennai_overpass_drivable.json with ijson rather than json.load --
    this is the same 70 MB cached Overpass response T0.2 fetched; streaming keeps this
    script's own memory footprint small and independent of how that file grows, consistent
    with T0.2's documented lesson that this machine has genuinely limited free RAM (as little
    as ~0.4-1.1 GB measured directly), not just a library-choice problem.
    """
    ways = []
    with open(WAYS_PATH, "rb") as f:
        for element in ijson.items(f, "elements.item"):
            if element.get("type") != "way":
                continue
            geometry = element.get("geometry")
            if not geometry:
                continue
            # ijson yields decimal.Decimal for numbers by default; cast to float since
            # every downstream calculation (haversine, grid-cell math) expects it.
            pts = [
                (float(g["lat"]), float(g["lon"]))
                for g in geometry
                if "lat" in g and "lon" in g
            ]
            if len(pts) < 2:
                continue
            tags = element.get("tags", {})
            way_id = element.get("id")
            ways.append(
                {
                    "id": int(way_id) if way_id is not None else None,
                    "highway": tags.get("highway"),
                    "pts": pts,
                    "name": tags.get("name"),
                }
            )
    return ways


def build_grid_index(
    ways: list[dict], cell_deg: float
) -> dict[tuple[int, int], list[int]]:
    index: dict[tuple[int, int], list[int]] = {}
    for i, way in enumerate(ways):
        cells = set()
        for lat, lon in way["pts"]:
            cells.add((int(lat / cell_deg), int(lon / cell_deg)))
        for cell in cells:
            index.setdefault(cell, []).append(i)
    return index


def point_segment_distance_m(
    p: tuple[float, float], a: tuple[float, float], b: tuple[float, float]
) -> float:
    """Approximate point-to-segment distance in metres. Chennai spans <0.5 deg lat/lon, so a
    local equirectangular projection (scaling longitude by cos(latitude)) is accurate to a
    few metres here -- adequate for "which street is this," not for survey-grade geometry.
    """
    lat0 = p[0]
    m_per_deg_lat = 111320.0
    m_per_deg_lon = 111320.0 * math.cos(math.radians(lat0))

    def to_xy(pt: tuple[float, float]) -> tuple[float, float]:
        return (pt[1] * m_per_deg_lon, pt[0] * m_per_deg_lat)

    px, py = to_xy(p)
    ax, ay = to_xy(a)
    bx, by = to_xy(b)
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return math.hypot(px - ax, py - ay)
    t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    cx, cy = ax + t * dx, ay + t * dy
    return math.hypot(px - cx, py - cy)


def snap_to_nearest_way(
    point: tuple[float, float],
    ways: list[dict],
    index: dict[tuple[int, int], list[int]],
    cell_deg: float,
) -> dict | None:
    """Grid-ring nearest-way search.

    **Bug fixed 2026-09-14 (independent review):** the previous version stopped at the first
    non-empty ring and returned the best match found there, without checking whether a *closer*
    way existed one ring further out -- a cell that happens to be in a farther ring can still
    contain a way closer than anything in a nearer ring that just happens to have content. The
    review reproduced this against the real 402-candidate output: 23/402 (5.7%) resolved to a
    different, closer way once this was fixed, including two cases 700-900 m off. The correct
    termination condition is not "the first ring with anything in it" but "no ring further out
    could possibly contain anything closer than what's already been found" -- implemented below
    via a conservative per-ring minimum-distance bound, not a fixed ring count past the first hit.
    """
    lat, lon = point
    cx, cy = int(lat / cell_deg), int(lon / cell_deg)
    # Conservative (i.e. an underestimate, which is the safe direction for a lower bound):
    # metres per degree of longitude shrinks with latitude, and is always <= metres per degree
    # of latitude, so using it for both axes never overstates how close a farther ring could be.
    m_per_deg = 111_320.0 * math.cos(math.radians(lat))

    best_way, best_dist = None, None
    max_radius = (
        60  # ~60 * (cell_deg * m_per_deg) ~= 65 km -- far beyond Chennai's extent
    )
    for radius in range(max_radius + 1):
        # Any cell at this ring is at least (radius - 1) whole cell-widths from the query
        # point, in the worst case where the point sits at the very edge of its own cell.
        ring_min_dist_m = max(0, radius - 1) * cell_deg * m_per_deg
        if best_dist is not None and ring_min_dist_m > best_dist:
            break

        cell_ids: set[int] = set()
        for dx in range(-radius, radius + 1):
            for dy in range(-radius, radius + 1):
                if max(abs(dx), abs(dy)) != radius:
                    continue
                cell_ids.update(index.get((cx + dx, cy + dy), []))

        for i in cell_ids:
            way = ways[i]
            pts = way["pts"]
            for a, b in itertools.pairwise(pts):
                d = point_segment_distance_m(point, a, b)
                if best_dist is None or d < best_dist:
                    best_dist, best_way = d, way

    if best_way is None:
        return None
    return {
        "way_id": best_way["id"],
        "street_name": best_way.get("name"),
        "highway": best_way.get("highway"),
        "distance_m": round(best_dist, 1),
    }


# ---------------------------------------------------------------------------------------
# Step 6: coarse basin heuristic
# ---------------------------------------------------------------------------------------


def distance_stats(distances_m: list[float]) -> dict:
    ds = sorted(distances_m)
    return {
        "min": round(ds[0], 1),
        "median": round(ds[len(ds) // 2], 1),
        "p90": round(ds[int(len(ds) * 0.9)], 1),
        "max": round(ds[-1], 1),
    }


def basin_label(lat: float) -> str:
    for min_lat, label in BASIN_BANDS:
        if lat > min_lat:
            return label
    return "unknown"


# ---------------------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------------------


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Parsing {KML_PATH.name}...")
    zones = load_flood_zones()
    print(f"  {len(zones)} zones total")

    high_risk = [z for z in zones if z["category"] in HIGH_RISK_CATEGORIES]
    print(f"  {len(high_risk)} High/Very High zones")

    print("Cluster-radius sensitivity sweep (see this script's docstring)...")
    radius_sweep = {}
    for r in CLUSTER_RADIUS_SWEEP_M:
        n = len(cluster_points(high_risk, r))
        radius_sweep[str(int(r))] = n
        print(f"  radius={r:.0f}m -> {n} clusters")

    print(f"Clustering within {CLUSTER_RADIUS_M} m (the chosen default)...")
    clusters = cluster_points(high_risk, CLUSTER_RADIUS_M)
    print(f"  {len(clusters)} clusters")

    print(f"Streaming {WAYS_PATH.name} (this is the slow step)...")
    ways = load_drivable_ways()
    print(f"  {len(ways)} drivable ways with geometry")
    index = build_grid_index(ways, GRID_CELL_DEG)

    candidates = []
    n_snapped = 0
    n_michaung_matched = 0
    n_far_snap = 0
    basin_counts: dict[str, int] = {}
    for i, c in enumerate(clusters):
        point = (c["lat"], c["lon"])
        snap = snap_to_nearest_way(point, ways, index, GRID_CELL_DEG)
        if snap:
            n_snapped += 1
            # >300 m means the nearest drivable way is far enough from the cluster centroid
            # that the snap is probably crossing open ground (e.g. the Pallikaranai marsh
            # itself) or the edge of this dataset's coverage, not "the road at this spot" --
            # flag it rather than presenting every snap as equally confident.
            if snap["distance_m"] > 300:
                n_far_snap += 1
                snap["low_confidence_far_snap"] = True
        lead = nearest_michaung_lead(*point)
        if lead:
            n_michaung_matched += 1
        basin = basin_label(c["lat"])
        basin_counts[basin] = basin_counts.get(basin, 0) + 1

        candidates.append(
            {
                "candidate_id": f"tw1-{i:04d}",
                "centroid_lat": round(c["lat"], 6),
                "centroid_lon": round(c["lon"], 6),
                "n_source_zones": c["n_members"],
                "source_categories": sorted(c["member_categories"]),
                "total_zone_area": round(c["total_area"], 2),
                "snapped_edge": snap,
                "michaung_2023_cross_check": lead,
                "basin_label_heuristic": basin,
                "basin_label_confidence": "heuristic_unverified",
                "resident_name": None,
                "resident_signoff": False,
            }
        )

    # Highest-confidence first: cross-checked against 2023 press AND resolved to a real edge.
    candidates.sort(
        key=lambda c: (
            (
                0
                if c["michaung_2023_cross_check"]
                and c["michaung_2023_cross_check"]["status"] == "flooded"
                else 1
            ),
            0 if c["snapped_edge"] else 1,
            -c["total_zone_area"],
        )
    )

    watchlist_path = OUT_DIR / "watchlist_candidates.json"
    with open(watchlist_path, "w", encoding="utf-8") as f:
        json.dump(candidates, f, indent=2)

    manifest = {
        "task": "T-W1 -- watchlist build (automatable portion only, see this script's top comment)",
        "generated": TODAY,
        "source_kml": str(KML_PATH.relative_to(ROOT)),
        "source_ways": str(WAYS_PATH.relative_to(ROOT)),
        "total_zones_in_kml": len(zones),
        "high_risk_zones_used": len(high_risk),
        "cluster_radius_m": CLUSTER_RADIUS_M,
        "cluster_radius_choice_is_unvalidated": True,
        "cluster_count_by_radius_m": radius_sweep,
        "candidate_count": len(candidates),
        "snapped_to_osm_edge": n_snapped,
        "unsnapped": len(candidates) - n_snapped,
        "snap_distance_m_low_confidence_gt_300m": n_far_snap,
        "snap_distance_m_stats": distance_stats(
            [c["snapped_edge"]["distance_m"] for c in candidates if c["snapped_edge"]]
        ),
        "michaung_2023_cross_checked": n_michaung_matched,
        "basin_heuristic_counts": basin_counts,
        "target_range": "150-200 per docs/IMPLEMENTATION_PLAN.md T-W1",
        "target_range_note": (
            f"{len(candidates)} candidates is roughly {round(len(candidates) / 175, 1)}x "
            "the 150-200 target -- these are pre-review candidates (resident_signoff: "
            "false throughout, not final points), and the resident map review is expected "
            "to prune this substantially, not just rubber-stamp it."
        ),
        "not_done_still_pending": [
            (
                "cluster-radius validation -- candidate_count is genuinely sensitive to "
                "this choice (see cluster_count_by_radius_m); 300m is a documented "
                "default, not a validated one"
            ),
            (
                "way_id / street_name are resolved against a LIVE, unpinned Overpass "
                "snapshot (scripts/fetch_chennai_drivable_ways.py) -- provisional, and "
                "will likely need re-resolution once T1.3's real graph build exists "
                "against the pinned Geofabrik extract"
            ),
            (
                "basin label verified against a real GIS shapefile -- currently a "
                "coarse latitude-band heuristic (basin_label_confidence: "
                "heuristic_unverified) that is KNOWN to be directionally wrong for some "
                "points, not just imprecise: it has no longitude term, so an inland "
                "point at a low-enough latitude can be mislabelled 'Kovalam' (a coastal "
                "basin) purely for being far south, regardless of actual distance from "
                "the coast"
            ),
            (
                "each point named as a resident would say it (resident_name is null "
                "throughout -- this needs a person who knows the city, not an LLM guess)"
            ),
            (
                "the resident map-review acceptance test itself -- book it with a named "
                "person and a date, per docs/IMPLEMENTATION_PLAN.md T-W1"
            ),
            (
                "cross-check against the actual 2015 stagnation corpus (not located on "
                "this machine as a separate structured dataset -- only the Michaung 2023 "
                "press leads and the single 2026 GCC hazard-zone KML were available; see "
                "this script's top comment)"
            ),
            (
                "GCC/OpenCity source coverage gap, verified: the KML's longitude range "
                "bottoms out at 80.1285, east of the Mudichur/Varadharajapuram/Old "
                "Perungalathur corridor lead (80.1180) -- only 2 zones (0 High/Very High) "
                "fall within 10 km of that lead, versus 1,189-3,869 for the other four "
                "Michaung leads. Almost certainly a Greater Chennai Corporation boundary "
                "artifact (Mudichur/Perungalathur sit in Tambaram Corporation). No "
                "candidate in this file is near this lead, at any cluster radius -- this "
                "is a missing primary source, not a tuning problem. See "
                "docs/DECISIONS.md."
            ),
        ],
    }
    with open(RESULTS_DIR / "result.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print("\n=== Summary ===")
    for k, v in manifest.items():
        if k != "not_done_still_pending":
            print(f"  {k}: {v}")
    print("  not_done_still_pending:")
    for item in manifest["not_done_still_pending"]:
        print(f"    - {item}")
    print(f"\nWrote {watchlist_path.relative_to(ROOT)}")
    print(f"Wrote {(RESULTS_DIR / 'result.json').relative_to(ROOT)}")


if __name__ == "__main__":
    main()
